"""drop ping placeholder

Revision ID: a55610baaaea
Revises: 663a4f3ed52a
Create Date: 2026-05-02 16:28:22.267313+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a55610baaaea"
down_revision: str | Sequence[str] | None = "663a4f3ed52a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ping")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ping",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("message", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
